################################################################################
# Ansible playbook to create a new Odoo instance for example: https://new_instance.example.com
# Author: César Granados Carrillo a.k.a CsarGrnds
#
# Execute the playbook simply type: ansible-playbook create_instance.yml -e "system_name=new_instance name domain=example.com"
#
################################################################################
---
- name: Odoo Operations Automation
  hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: Create Odoo Instance
    ansible.builtin.include_role:
      name: create_instance