---
- name: Install and configure Odoo
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
  - name: Collect only needed gather_facts
    ansible.builtin.setup:
      filter: "{{ item }}"
    loop:
      - ansible_distribution_release
      - ansible_date_time
      - ansible_hostname

  tasks:
  - ansible.builtin.include_role:
      name: odoo_install
  