---
- name: Create init file
  ansible.builtin.template:
    src: odoo-server
    dest: /etc/init.d/{{ odoo_config }}
    mode: '0755'

- name: Enable Odoo to start at system boot
  ansible.builtin.command: update-rc.d {{ odoo_config }} defaults

- name: Stop Odoo service, if started
  ansible.builtin.service:
    name: "{{ odoo_config }}"
    state: stopped
  ignore_errors: true

- name: Start Odoo service, if stopped
  ansible.builtin.service:
    name: "{{ odoo_config }}"
    state: started