---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - git
      - python3
      - python3-pip
      - build-essential
      - wget
      - python3-dev
      - python3-venv
      - python3-wheel
      - libxslt-dev
      - libzip-dev
      - libldap2-dev
      - libsasl2-dev
      - python3-setuptools
      - node-less
      - libpng12-0
      - gdebi
    state: present
    
- name: Create download directory for requirements file 
  ansible.builtin.file:
    path: /tmp/odoo
    state: directory

- name: Download requirements files for Odoo {{ odoo_version }}
  ansible.builtin.get_url:
    url: https://github.com/odoo/odoo/raw/{{ odoo_version }}/requirements.txt
    dest: /tmp/odoo

- name: Install Python packages from requirements file
  ansible.builtin.pip:
    requirements: /tmp/odoo//requirements.txt

- name: Install nodejs and npm 
  ansible.builtin.apt:
    name:
      - nodejs 
      - npm
    state: present

#- name: Install rtlcss
#  ansible.builtin.npm:
#    name: rtlcss
#    global: yes
#  ignore_errors: true