---
- name: Replace value in file
  ansible.builtin.lineinfile:
    path: /etc/{{ odoo_config }}.conf
    regexp: 'proxy_mode =.*$'
    line: 'proxy_mode = True'
    state: present
    backup: yes
  notify: Restart Odoo service

- name: Replace value in file
  ansible.builtin.lineinfile:
    path: /etc/{{ odoo_config }}.conf
    regexp: 'dbfilter =.*$'
    line: 'dbfilter = ^%d$'
    state: present
    backup: yes
  notify: Restart Odoo service
